gpu_id: 0
multi_gpus: True
num_workers: 4
seed: 666
exp_name: 'expMSVD-QA_Resnet_GAFN_layer5'

train:
  lr: 0.0001
  batch_size: 32
  restore: False
  max_epochs: 15
  word_dim: 300
  motion_dim: 2048 #1024 2048
  appearance_dim: 2048 #1536 2048
  module_dim: 512
  glove: True


val:
  flag: True

test:
  test_num: 0
  write_preds: False

dataset:
  name: 'msvd-qa'
  question_type: 'none'
  data_dir: 'data/msvd-qa'
  save_dir: 'results/'
  appearance_feat: '{}_appearance_resnet_feat.h5' 
  motion_feat: '{}_motion_resnetxt_feat.h5'
  appearance_dict: '{}_resnet_appearance_feat_dict_512.h5'
  motion_dict: '{}_resnetxt_motion_feat_dict_512.h5'