gpu_id: 0
multi_gpus: True
num_workers: 4
seed: 666
exp_name: 'expTGIF-QACount-ResNetv2'

train:
  lr: 0.0001
  batch_size: 32
  restore: False
  max_epochs: 10
  word_dim: 300
  motion_dim: 2048 #1024
  appearance_dim: 2048 #1536
  module_dim: 512
  glove: True


val:
  flag: True

test:
  test_num: 0
  write_preds: False

dataset:
  name: 'tgif-qa'
  question_type: 'count'
  data_dir: 'data/tgif-qa/count'
  save_dir: 'results/'
  appearance_feat: '{}_{}_appearance_feat_resnet.h5'
  motion_feat: '{}_{}_motion_feat_resnetxt.h5'
  appearance_dict: '{}_count_resnet_appearance_feat_dict_512.h5'
  motion_dict: '{}_count_resnetxt_motion_feat_dict_512.h5'